SHOPS = ["osher_ad", "keshet", "super_dosh"]
ITEMS = [
    ("almond_milk", "almond milk"),
    ("apple", "apple"),
    ("avocado", "avocado"),
    ("baby_wipes", "baby wipes"),
    ("banana", "banana"),
    ("batata", "batata"),
    ("black_olives", "black olives"),
    ("bread", "bread"),
    ("broccoli", "broccoli"),
    ("butter", "butter"),
    ("carrot", "carrot"),
    ("cashew_salted", "cashew salted"),
    ("cheese_yellow", "cheese yellow"),
    ("cinnamon_buns", "cinnamon buns"),
    ("conditioner_laundry", "conditioner laundry"),
    ("corn", "corn"),
    ("cottage_cheese", "cottage cheese"),
    ("crackers", "crackers"),
    ("cucumbers", "cucumbers"),
    ("dates", "dates"),
    ("eggs", "eggs"),
    ("feta_cheese", "feta cheese"),
    ("frozen_fruits", "frozen fruits"),
    ("green_onion", "green onion"),
    ("hand_soap", "hand soap"),
    ("hasa", "hasa"),
    ("hering_in_oil", "hering in oil"),
    ("juice", "juice"),
    ("kabanos", "kabanos"),
    ("kube_frozen", "kube frozen"),
    ("laundry_capsules_white", "laundry capsules white"),
    ("laundry_capsules_color", "laundry capsules color"),
    ("lemon", "lemon"),
    ("maadan", "maadan"),
    ("mint_fresh", "mint fresh"),
    ("mushrooms", "mushrooms"),
    ("mushrooms_fresh", "mushrooms fresh"),
    ("oatmeals", "oatmeals"),
    ("olive_oil", "olive oil"),
    ("paper_towels", "paper towels"),
    ("parsley", "parsley"),
    ("peanuts_salted", "peanuts salted"),
    ("pesto", "pesto"),
    ("pickled_tomatoes", "pickled tomatoes"),
    ("pizza_x3", "pizza x3"),
    ("potato_white", "potato white"),
    ("prune", "prune"),
    ("shnitzelonim", "shnitzelonim"),
    ("sour_cherry_compote", "sour cherry compote"),
    ("sour_cream", "sour cream"),
    ("spinach", "spinach"),
    ("strawberry", "strawberry"),
    ("sugar_brown", "sugar brown"),
    ("sunflower_seeds", "sunflower seeds"),
    ("tangerine", "tangerine"),
    ("tissues", "tissues"),
    ("toilet_paper", "toilet paper"),
    ("toilet_wet_tissues", "toilet wet tissues"),
    ("tomato_paste", "tomato paste"),
    ("tomatoes", "tomatoes"),
    ("tomatoes_cherry", "tomatoes cherry"),
    ("toothpaste", "toothpaste"),
    ("tortilla", "tortilla"),
    ("tuna_small_rio", "tuna small rio"),
    ("vanish", "vanish"),
    ("vareniki", "vareniki"),
    ("walnuts", "walnuts"),
    ("wine", "wine"),
]

CATEGORIES = [
    ("fruits_veggies", "fruits veggies"),
    ("hygiene_chemicals", "hygiene chemicals"),
    ("cans", "cans"),
    ("preserves", "preserves"),
    ("dairy", "dairy"),
    ("grain", "grain"),
    ("drinks", "drinks"),
    ("meat_fish", "meat fish"),
    ("snacks", "snacks"),
]
